### ISSUE TITLE
FIR->Symmetry values are not defined

### ISSUE THREAD

**Issue by chad-iris** [FDSN/StationXML#71]
The values for the `FIR->Symmetry` element need definition.   They are currently defined in the `FIRType` definition as:

```XML
<xs:element name="Symmetry">
    <xs:simpleType>
        <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="NONE"/>
            <xs:enumeration value="EVEN"/>
            <xs:enumeration value="ODD"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>
```

These values are directly related to the symmetry code of SEED Blockettes 61/41 that define them as:

```
A — No Symmetry - all Coefficients are specified
B — Odd number Coefficients with symmetry
C — Even number Coefficients with symmetry
```

**Comment by crotwell** [comment]
fixed in PR #89

**Comment by jschaeff** [comment]
> fixed in PR #89

Does this PR take care of #100 and #70 ?

I was looking at the changes in PR #89 and the comments seem to somehow clarify the ambiguity, but I can't tell for sure.

**Comment by crotwell** [comment]
I don't think so, #71  requires an additional PR as it deals with the documentation that is external to the schema annotations.

I marked #100 as a duplicate of #70, but there is quite a bit of overlap.

**Comment by PetrColinSky** [comment]
I very much like the explanation given by @mikehagerty in issue #100. It is 100% clear. The best would be to embed it somewhere in the documentation as a whole paragraph including the example.

I got bit lost in the references to the PRs: @jschaeff asks, if PR #89 takes care of issue #71, right? And @crotwell replies, he doesn't think so. But here we are in the issue #71 and above it says, it was fixed in PR #89.

**Comment by crotwell** [comment]
Sorry, I confused myself. PR #89 does fix this issue ( #71 ) but does not fix #70. I marked #100 as a duplicate of #70, so neither of those is fixed by this PR.

Just to summarize, this issue ( #71 ) deals with the annotation embedded in the schema, ie section 2, while #100 and #70 deal with the longer explanation in section 3.

Probably all three of these issues should be resolved at the same time as they are closely related, but my PR only deals with section 2.

**Comment by crotwell** [comment]
closing this issue, but may still need to do more on #70 which is related.
